server:
  port: 8301
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudstudy
    username: root
    password: root
security:
  oauth2:
    client:
      #不多说了
      client-id: web
      client-secret: 654321
      #Token获取地址 使用@EnableResourceServer作为资源服务器时不需要这配置
      #access-token-uri: http://localhost:8500/sso/oauth/token
      #验证页面地址 使用@EnableResourceServer作为资源服务器时不需要这配置
      #user-authorization-uri: http://localhost:8500/sso/oauth/authorize
    resource:
      #Token信息获取和校验地址
      token-info-uri: http://localhost:8500/sso/oauth/check_token