spring:
# 全部移入nacos
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cloudstudy
#    username: root
#    password: root
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        namespace: 3206fdf7-a5a1-48d2-9886-e5efaf2d4b09